### ISSUE TITLE
Write Developers Guide (code management plan)

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/regional_workflow#135]
Take a look at DG being put together for the UFS v0.1 release and update it as needed for the SAR workflow repository

**Comment by jwolff-ncar** [comment]
I talked to Ligia about the Developer's Guide for the Weather Model. What was provided by EMC can be found at: https://github.com/ufs-community/ufs-weather-model/wiki/Developing-Code

The CCPP Developer's Guide can also be used as a good example to follow: https://dtcenter.org/GMTB/v3.0/ccpp_tech_guide/

**Comment by jwolff-ncar** [comment]
@JulieSchramm @fentoad72 Let's update this issue as the "Developers Guide" (currently: https://docs.google.com/document/d/1Vmg4IILfmcazctJJ_tQxPsQsBHpBKN9osNKBok3mTX4/edit) for the regional_workflow (future  SRweather App?) is included into the repo as RST files. Also use the CCPP documentation as a guide for what this should look like.

This would be another chapter in the Users' Guide too.

**Comment by jwolff-ncar** [comment]
Use this Google Doc as a starting point (https://docs.google.com/document/d/1Vmg4IILfmcazctJJ_tQxPsQsBHpBKN9osNKBok3mTX4/edit) and incorporate other necessary information following the MRW application and CCPP.

**Comment by jwolff-ncar** [comment]
Relevant info from UFS SC
https://docs.google.com/document/d/1zzS3VZndGucI6MFR6o-26QLl0eSbaKhd2eynrxMDxmU/edit?pli=1#
https://ufscommunity.org/wp-content/uploads/2019/10/20180608_UFS_Infrastructure_Repositories_Sub-Group.pdf

**Comment by jwolff-ncar** [comment]
Related to issue created here: https://github.com/ufs-community/ufs-srweather-app/issues/141

**Comment by mkavulich** [comment]
Done: https://github.com/ufs-community/regional_workflow/wiki/Code-development-and-review-in-the-regional_workflow-repository
