### ISSUE TITLE
Create script/utility for plotting compute grid vs write grid

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/regional_workflow#165]
- [x] Create initial script
 - [ ] Modify to account for stretching/rotation
 - OR [ ] Potentially call existing code in make_hgrid

**Comment by JacobCarley-NOAA** [comment]
Tagging @DusanJovic-NOAA as the fv3grid utility *should* already handle this.

**Comment by mkavulich** [comment]
I actually already got an email response from @DusanJovic-NOAA , it was buried in my inbox and I somehow missed it. I will see if that meets all the requirements I need.

**Comment by mkavulich** [comment]
Need to investigate the current options for this

**Comment by gsketefian** [comment]
@mkavulich This can currently be done in a systematic way only via the NCL scripts I have, which are not user-friendly (so really I'm the only one who knows how to use them).  The scripts need to be rewritten in python (I'd like to do that so I can get better at python plotting, but if someone else really wants to, they can take it on).

**Comment by JacobCarley-NOAA** [comment]
We do have python scripts that will plot the domains once the basic ESG grid is created. It's not too hard to use. Tagging @BenjaminBlake-NOAA as he's probably the one who has used it more recently. Let us know.

**Comment by gsketefian** [comment]
@JacobCarley-NOAA Sorry I got this issue confused with #9, which is more about generation of the grid parameters.  Will comment in that one.

**Comment by jwolff-ncar** [comment]
Are these the scripts described in @chan-hoo documentation? It has been awhile since I have looked at that document now that we have the officially released SRW App Users Guide. Does it make sense to leverage those or should those not be widely shared? If it makes sense, we can add them to the repo and document them in the SRW App UG (chapter 10) for the develop branch.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/400
