### ISSUE TITLE
Change jinja template "model_configure" to yaml

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#331]
@christinaholtNOAA had the following recommendation in PR #321:

> I do think that a Jinja template for this file limits you very greatly, though. You cannot change any field that is not already templated. The file is a yaml file and can be treated as such, building it the same way you'd build a namelist, but with yaml output instead of a Fortran namelist.

**Comment by mkavulich** [comment]
Resolved by #321
