### ISSUE TITLE
On Orion, debug miniconda3's regional_workflow environment

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#341]
In the Orion modulefiles, the regional_workflow environment is loaded as follows:
```
module use -a /apps/contrib/miniconda3-noaa-gsl/modulefiles
module load miniconda3
if [module-info mode load] {
  system "conda activate regional_workflow"
}
```
With this, occasionally tasks fail with an error about PS1 being an undefined variable.  The circumstances under which this happens is unclear, but this issue needs to be fixed.  The following change to the above seems to fix the problem, but it is not an ideal solution:
```
module use -a /apps/contrib/miniconda3-noaa-gsl/modulefiles
module load miniconda3
if [module-info mode load] {
  system "export PS1=\${PS1:-} ; conda activate regional_workflow"
}
```
A better solution would be to modify the script/function that "conda activate" calls so that PS1 is always defined.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, was this resolved with work leading up to the first release?

**Comment by mkavulich** [comment]
Conda environment issues have been solved on Orion.
