### ISSUE TITLE
Introduce unit tests to regional workflow

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [ufs-community/regional_workflow#38]

**Comment by jwolff-ncar** [comment]
Establish several baseline tests (i.e. the config.sh file for each) and come up with short names for them.
  - regional_001, regional_002, regional_003
- [ ] Add description of what each test checks

**Comment by jwolff-ncar** [comment]
FYI: https://github.com/ufs-community/ufs-weather-model/wiki/Regression-Test-Policy-for-Weather-Model-Platforms-and-Compilers

**Comment by gsketefian** [comment]
This is not an issue that will be resolved with one or two PRs but will be an ongoing effort.  I have started including unit test scripts in my new PRs (after 5/18/2021), but it will be a long road to getting "complete coverage".  

Also, I wonder if anyone knows whether github can provide coverage information for shell scripts like it does for fortran code (as demonstrated by Ed Hartnett in a recent presentation).

**Comment by mkavulich** [comment]
Unit tests have been introduced to the workflow generation; any improvements or expansion of unit tests is best handled by a new issue if necessary.
