### ISSUE TITLE
set_namelist.py python script fails if first namelist variable in config = { ... } has a null value

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#386]
The `set_namelist.py` script fails if the configuration it is passed (via the `-u` flag) is such that the first variable has a null value.

For example, the following bash code will fail on the call to `set_namelist.py` if `${fn_atm_nemsio}` is set to a null value:
```
settings="
'config': {
 'atm_files_input_grid': ${fn_atm_nemsio},
...
 'fix_dir_input_grid': ${FIXgsm},
...
 'fix_dir_target_grid': ${FIXLAM},
}
"
${USHDIR}/set_namelist.py -q -u "$settings" -o ${nml_fn}
```
Note that the second, third, etc variables (e.g. `fix_dir_input_grid`, which would happen if `${FIXgsm}` was null) can be null; in such cases, `set_namelist.py` will still succeed.  It only fails if the first variable is null.

The temporary fix is to place the empty value that `${fn_atm_nemsio}` represents in escaped double quotes.  So the following will work:
```
settings="
'config': {
 'atm_files_input_grid': \"${fn_atm_nemsio}\",
...
 'fix_dir_input_grid': ${FIXgsm},
...
 'fix_dir_target_grid': ${FIXLAM},
}
"
${USHDIR}/set_namelist.py -q -u "$settings" -o ${nml_fn}
```
For consistency, `set_namelist.py` should be modified so that the first namelist variable can also be null, or so that all empty variables need to be placed in escaped double quotes.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, is this still an problem?

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/355
