### ISSUE TITLE
develop:  Create a "debug" or "developer mode" to create a self-contained run directory for further testing

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/regional_workflow#393]
With the addition of a "debug" or "developer mode" user-defined flag in config.sh, the option would exist to place all files necessary to replicate a simulation within the run directory, regardless of workflow mode (community or NCO).  The run directory would contain copies of executables, copies of all soft links/fix files, namelists, etc.  In addition, this flag would generate a run script with all relevant job card information for that cycle, enabling the user to resubmit the FV3 job to queue manually.  In addition, the run directory would then be self-contained, allowing others to copy the full directory and test changes in their own workspace.

@gsketefian @climbfuji @christinaholtNOAA Chunhua Zhou Joe Olson

**Comment by gsketefian** [comment]
After speaking with @joeolson42, the debug-related tasks he'd like to facilitate using any given run directory (that this "develop" mode should address) are as follows:
* Rerun with different module loads.
* Rebuild executable and rerun (including debugging flags on).
* Rerun with different physics suite.
* Rerun with different MPI layout.
* Rerun with different input.nml parameters.

Also, there is a request from GSL to:
* Place log files in the run directory to make them easier to access.
*

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/399
