### ISSUE TITLE
Point paths for HRRRX to HRRR on HPSS, remove references to HRRRX elsewhere in workflow. Remove staged HRRRX data.

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#405]

**Comment by JeffBeck-NOAA** [comment]
Why is this necessary?

**Comment by mkavulich** [comment]
HRRRX and RAPX data has been removed from Hera, and staged data removed from Hera. I will ensure the other platforms with staged data that I have access to (Orion, Cheyenne, Jet) get the same treatment.

@christinaholtNOAA will your PR #681 resolve this problem for data from HPSS?

**Comment by christinaholtNOAA** [comment]
The new paths were included as part of #667, and are being implemented as part of #681

**Comment by mkavulich** [comment]
Fixed entirely by #681, #744
