### ISSUE TITLE
Determine why WE2E test grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha in release branch is failing in run_fcst task after hour 2

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#406]

**Comment by jwolff-ncar** [comment]
Is this still an issue @gsketefian? We should look at date and whether experimental or operational files were used. This came up a lot in advance of the release but I don't know where it was left after the release.

**Comment by JeffBeck-NOAA** [comment]
Since the RRFS_v1alpha SDF is no longer included in the SRW App, I think we can close this PR.
