### ISSUE TITLE
Get changes to config_defaults.sh made in Ch. 5 of documentation back into config_defaults.sh in repo (both release and develop branches)

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#432]

**Comment by mkavulich** [comment]
There also may be some useful documentation in the comments that were removed in #617

**Comment by gspetro-NOAA** [comment]
Can this issue be closed now that the develop branch is updated, and any changes will therefore be reflected in the SRW App v2 release?

**Comment by gsketefian** [comment]
Yes.
