### ISSUE TITLE
Centralize the way machine-dependent workflow parameters are set

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#447]
Workflow parameters such as APRUN that depend only on the machine/platform should be grouped and set in one place, e.g. in some sort of environment file for that machine.

**Comment by mkavulich** [comment]
The solution to this issue should also incorporate rocoto-specific settings (such as processors per node for certain tasks).

The OMP parameters mentioned in #452 should fall under this issue as well.

**Comment by mkavulich** [comment]
Done with #666
