### ISSUE TITLE
Allow different forecast lengths for different cycles 

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#456]
Currently, FCST_LEN_HRS is a scalar specifying the forecast length (in hours).  Introduce the option to make this an array (of the same size as CYCL_HRS) that specifies the forecast length of each cycle.

**Comment by jwolff-ncar** [comment]
Curious, is this driven by any project needs? If not, I would move this to low priority.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/370
