### ISSUE TITLE
Adapt user-staged external model files feature for ensembles

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#468]
When running ensembles (`DO_ENSEMBLE="TRUE"`) and using user-staged external model data (i.e. when `USE_USER_STAGED_EXTRN_FILES="TRUE"`), it is currently not possible to get different external model IC/LBC files for each ensemble member.  That is because when the workflow uses the variables `EXTRN_MDL_SOURCE_BASEDIR_ICS` and `EXTRN_MDL_SOURCE_BASEDIR_LBCS` to create paths in which to look for the external model files, those paths do not depend on the ensemble member; only a cycle date gets appended to the end of `EXTRN_MDL_SOURCE_BASEDIR_[ICS|LBCS]` to get those paths, e.g.

`extrn_mdl_source_dir="${EXTRN_MDL_SOURCE_BASEDIR_ICS}/$CDATE"
`

When running ensembles, this should be changed to something like this:

`extrn_mdl_source_dir="${EXTRN_MDL_SOURCE_BASEDIR_ICS}/${ensmem_name}/$CDATE"
`

where `ensmem_name` would be something like "mem01", "mem02", etc.

See [this PR](https://github.com/NOAA-GSL/regional_workflow/commit/3d9506f5b925ce25d3092526e09b272aed3d7690) for an example of how this has been done by @chunhuazhou.

**Comment by chunhuazhou** [comment]
For me using GEFS, there is no $CDATE, the date information is in the filenames (for example, 2109800000012). And the "ensmem_name" might be different from the setting for the run directory (mem1, mem2, ...). For GEFS, it is gep01, gep02, ...

**Comment by chunhuazhou** [comment]
This commit has most information on initializing RRFS ensemble from GEFS: https://github.com/NOAA-GSL/regional_workflow/commit/55adbd11d025d1bb57ade2848a615766594ceb35

**Comment by gsketefian** [comment]
We'll definitely include a new variable for the ensemble base name, e.g. `ENSMEM_BASENAME="gep"`, `"mem"`, etc.  

The problem with not having a cycle directory and instead having the file names have the cycle dates is that different models do this differently.  I tried to stick to a single standard where each cycle is in its own directory.  With this standardized approach, it is the user's responsibility to move their data into individual cycle directories and have names for their files that depend only on the forecast hour, so the LBC files would be, e.g.

`${EXTRN_MDL_BASEDIR_LBCS}/${ensmem_name}/${CDATE}/${extrn_mdl_fn_lbcs}`

where

```
ensmem_name="${ENSMEM_BASENAME}_${ensmem_num}"
extrn_mdl_fn_lbcs="${EXTRN_MDL_FILE_BASENAME_LBCS}_f${fhr}"
```

and `${ensmem_num}` is the ensemble member number ("01", "02", ...) and `$fhr` is the forecast hour ("03", "06", ...).  If we don't do some kind of standardization like this, we have to have specific code for each external model, which is a lot of messy code.  Maybe we'll end up having to do that AND have this standardized approach as the default.  We'll have to talk about this during the DTC-CAM meeting and probably contact you (@chunhuazhou) when starting to work on this.

**Comment by mkavulich** [comment]
This may be resolved if/when GSL fork is merged.
