### ISSUE TITLE
Remove the variable COMINgfs from the workflow?

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#471]
COMINgfs will be superseded by the more general (and soon to be user-specifiable) variables EXTRN_MDL_BASEDIR_[ICS|LBCS].  Talk to EMC/NCO about removing COMINgfs (since a lot of other variables don't stick to the strict NCO standards anyway).

**Comment by mkavulich** [comment]
Per feedback on #744, The "COMIN" naming standard is an NCO requirement.
