### ISSUE TITLE
Check in with EMC/NCO and get feedback on whether workflow is up to NCO standards

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#472]

**Comment by jwolff-ncar** [comment]
@JacobCarley-NOAA Is this something you would recommend doing? If so, how should this done?

**Comment by JacobCarley-NOAA** [comment]
My gut reaction is that a complete review might pretty time consuming. We may want to try and capture this via process, i.e. have the 'standards' be a part of the code review.

**Comment by mkavulich** [comment]
NCO review is ongoing, being handled outside of this issue. Since the issue is about "getting feedback", this issue is technically resolved.
