### ISSUE TITLE
When calling run_experiments.sh with testset_name is specified as a command line argument, prevent output from two different NCO-mode experiments from being written to same set of directories 

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#475]
When running a WE2E test that is in NCO mode and which uses the testset_name argument to run_experiments, make sure that a subdirectory named testset_name somewhere under nco_dirs is created and that STMP and PTMP are set to values that include this subdirectory.  This is necessary so that if two different NCO-mode experiments with the same name but different testset_name are launched, they use different STMP and PTMP directories under nco_dirs (otherwise, they will overwrite each other's output).

**Comment by panll** [comment]
I tested on Hera and don't see the problem. The issue has already been fixed.
