### ISSUE TITLE
make_grid tasks being cancelled/timing out on Jet due to "BadConstraints"

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/regional_workflow#495]
Presumably this is due to make_grid assuming 24 tasks per node on Jet, but not all partitions have 24 cores available per node (https://jetdocs.rdhpcs.noaa.gov/wiki/index.php/Jet_System_Overview). I left jobs running overnight hoping some nodes with more cores were open up, but at some point they were simply cancelled or timed out.

Either we need the capability to specify which Jet partition to submit to, or we need to reduce the requested cores per node.

**Comment by JeffBeck-NOAA** [comment]
@mkavulich, I'm trying to understand why this wasn't happening before...

**Comment by mkavulich** [comment]
@JeffBeck-NOAA I am as well; I haven't done much testing on Jet before, and apparently we have not been running regular end-to-end tests on Jet for some time because the run script is broken (points to an old path for data; I need to open a PR for that...).

I am running several tests on Jet now, and the make_grid tasks that happen to land on xjet are running smoothly (barely any queue wait). Another, nearly identical job (same domain and resolution, same number of nodes and cores requested) was assigned to kjet,sjet, and is hung in the queue with a "BadConstraints" note under reason. I don't have time to wait them out right now so I'm just going to kill that job and hope it lands on xjet next time.

**Comment by mkavulich** [comment]
Just an update: the pending job with a "BadConstraints" note finished just after I wrote the above message. So I think this has to do with how busy the machine is, and how many of which nodes are available.

Maybe this is not an issue aside from days with a very heavy machine load? I will move this issue to "low priority" for now but I do think we need to investigate more at some point...

**Comment by JeffBeck-NOAA** [comment]
It sounds like "BadConstraints" is related to available node/cores and is not a show-stopper for the job.  But I agree that we shouldn't be requesting 24 cores per node for all Jet partitions, since that's clearly not the case for older partitions.

**Comment by JeffBeck-NOAA** [comment]
I think we should re-frame this issue to implement variable cores per node on Jet partitions.  The question is how to do that when the node that's assigned is handled by the scheduler.

**Comment by mkavulich** [comment]
The "BadConstraints" message is part of the normal messaging of Jet queueing, this is no longer a relevant issue. The original problem may have been a temporary machine issue, as it is no longer affecting jobs.
