### ISSUE TITLE
Pass in MET version number through config.sh setting

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/regional_workflow#499]
## Description
MET version numbers are currently hard-coded in the config files under template/parm/met (currently: version = "V9.0.2";). 

## Solution
The MET version should be set in config.sh and passed as needed.

**Comment by PerryShafran-NOAA** [comment]
It should be noted that one easy way to do this is to simply comment that line out of the MET configuration files.  This is what I now do in my regular daily METplus runs.  Whatever version is being run will still be written out in the stat files.

**Comment by jwolff-ncar** [comment]
Closing this issue as this is no longer a concern given the restructuring to remove the MET config files and only use the METplus conf files.
