### ISSUE TITLE
Clean up regional_workflow wiki and add/remove certain sections

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/regional_workflow#519]
Update the regional_workflow wiki with any relevant changes.  Decide whether some portions should be migrated to the ufs-srweather-app or whether it can be removed all together (such as the FV3-LAM Workflow Setup and Execution section)

**Comment by mkavulich** [comment]
This is being handled by https://github.com/ufs-community/ufs-srweather-app/issues/351
