### ISSUE TITLE
Add CRTM synthetic satellite output capabilities for UPP

### ISSUE THREAD

**Issue by hertneky** [ufs-community/regional_workflow#543]
## Description
Users cannot currently output synthetic satellite products from UPP without modification to the exregional_run_post script to link external CRTM coefficient files to the UPP working directory. This is an important and desired capability.

## Solution
In config.sh:
Create a user defined variable that includes the path to the top CRTM fix file directory (e.g. CRTM_DIR).
Create a variable to switch on/off using CRTM (e.g. USE_CRTM=TRUE/FALSE)

In scripts:
Modify the exregional_run_post script to link/copy the fix files if USE_CRTM=TRUE

Other considerations include checking that the CRTM_DIR exists (USE_CRTM=TRUE and other checks, etc.

Note: The user will be responsible for manually downloading the CRTM fix files and staging them. These are available in the upp-v.9.0.0 release via a simple wget command.

## Related to (optional)
https://github.com/ufs-community/ufs-srweather-app/issues/151

**Comment by hertneky** [comment]
@JeffBeck-NOAA Is now a good time to add this enhancement?

**Comment by JeffBeck-NOAA** [comment]
@hertneky, if it's available now, yes, please feel free to open a PR!
