### ISSUE TITLE
Response to "Update syntax for latest version of lmod"

### ISSUE THREAD

**Issue by edwardstrobach** [ufs-community/regional_workflow#561]
I believe I'm experiencing the same issue (for me it is the inability to "import yaml").  I notice that when I reclone with the latest code that this becomes resolved.  However, I don't want to have to reclone.  Can I resolve this without recloning?  There has been a lot of work done already in the setup that I'm experimenting with.  In attempting to reclone I found that I wasn't able to add the suites I wanted to run with which is why I'm not sure I want to reclone.  There seems to be a namelist inconsistency, and since things change so frequently so often, it seems more trouble than it is worth to reclone and figure out all of these differences.  Thanks.

If there is interest in knowing the error that I have then I can share that as well.

**Comment by mkavulich** [comment]
@edwardstrobach Sorry you never got a response about this, if you need additional feedback please open a new issue in the UFS SRW App repository: https://github.com/ufs-community/ufs-srweather-app
