### ISSUE TITLE
make GWD orog generation into a function

### ISSUE THREAD

**Issue by JiliDong-NOAA** [ufs-community/regional_workflow#570]
## Description
@gsketefian Could you put the GWD orog generation in make_orog (e.g. the contents of "if [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then") into a separate function to make the scripts more modular? Thanks.

## Solution
Convert GWD orog generation to a function

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository:  https://github.com/ufs-community/ufs-srweather-app/issues/356
