### ISSUE TITLE
Use variable valid_vals_BOOLEAN everywhere that the array ( "TRUE" "true" "YES" "yes" ... "no" ) is defined

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#593]
## Description
The valid values that a boolean variable can take on should be defined in one place and used everywhere else to check if boolean variables are set to a valid value before using them.  (There is no "boolean" type in bash; we just mean a variable that should act like a boolean, i.e. not take on any values besides TRUE and FALSE.)  After PR #580 is merged, there will be a variable named `valid_vals_BOOLEAN` in `valid_param_vals.sh` that serves this purpose, and most instances of valid values being defined for a specific boolean, e.g. as follows for some variable named `SOME_FLAG`:

`  valid_vals_SOME_FLAG=( "TRUE" "true" "YES" "yes" "FALSE" "false" "NO" "no" )`

have been removed.  However, there are still a couple of bash utility scripts that contain such definitions: `set_boolean_to_TRUE_or_FALSE.sh` and `create_symlink_to_file.sh`.  These do not use `valid_vals_BOOLEAN` because they do not have access to it.  That's because `valid_vals_BOOLEAN` is defined in `valid_param_vals.sh`, and that is not sourced by the bash utility scripts.

## Solution
Move `valid_vals_BOOLEAN` out of `valid_param_vals.sh` to either `constants.sh` or a new file, and source that file in `valid_param_vals.sh` and in `source_util_funcs.sh`.  `valid_param_vals.sh` should only set valid values for experiment parameters that control the workflow behavior; `valid_vals_BOOLEAN` is more of a language or system variable that remains the same regardless of the experiment configuration.

**Comment by mkavulich** [comment]
No longer relevant with move to Python and yaml format config files
