### ISSUE TITLE
Consolidate verification footprint

### ISSUE THREAD

**Issue by michelleharrold** [ufs-community/regional_workflow#601]
## Description
PR #575 added ensemble verification to the workflow. In the review, it was identified that the deterministic and ensemble verification footprint could be compacted. There are currently multiple JREGIONAL_RUN_VX* and exregional* scripts that are fairly redundant; in addition, there are verification tasks in ush/templates/FVLAM_wflow.xml that could be reduced by using jinja.

## Solution
We can likely combine JREGIONAL_RUN_VX* into one since there are minimal differences [potentially by setting arguments or environment variables (in the XML)]. The same can be investigated for the exregional scripts. Jinja can be used to reduce the number of tasks in ush/templates/FVLAM_wflow.xml (e.g., VX_ENSGRID_MEAN_24h_TN) so that instead of having one for each GRID vs. POINT, cycle hour, and MEAN vs. PROB vs. nothing combination, those parameters are looped over in the XML using jinja syntax.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/381
