### ISSUE TITLE
Add operational HRRR model

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#602]
## Description
Preliminary objectives:
1) Add stanzas for operational HRRR model to `regional_workflow` scripts to allow obtaining external model files from NOAA HPSS.
2) Add appropriate WE2E tests for HRRR (not just HRRRX).  May require some mods to `run_experiments.sh` (in `release/public-v1` branch) and `run_WE2E_tests.sh` (in `develop` branch).

This should be done in both the `release/public-v1` and `develop` branches.

**Comment by gsketefian** [comment]
@jwolff-ncar Can you edit the description of this issue to make sure it addresses your concerns?  Thanks.

**Comment by mkavulich** [comment]
Closed via #653
