### ISSUE TITLE
Add support for Rocoto with generic LINUX platform

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/regional_workflow#610]
## Description
PR #402  added a capability to use a generic LINUX platform, but did not include support for workflow management with Rocoto.  

## Solution
The RRFS Cloud work required the use of Rocoto on a generic LINUX platform, and we would like to contribute that work back to the repository for a more complete functionality outside the supported platforms.

## Related to (optional)
PR #402

**Comment by mkavulich** [comment]
Addressed by #617
