### ISSUE TITLE
Add option for GEFS as an external model.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/regional_workflow#611]
## Description
Add the option to run with GEFS initial and lateral boundary conditions.

## Solution
A solution was incorporated for the RRFS Cloud work that allowed these external model files. I'd like to  contribute those changes to the develop branch.

The original work was done in collaboration with @chunhuazhou.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/368
