### ISSUE TITLE
Coordinate variables, upper-air levels and related thresholds in METplus-based deterministic and ensemble verification

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/regional_workflow#613]
## Description
Currently, ensemble verification contains a subset of the deterministic verification variables and upper-air levels.  Deterministic verification configuration files can be used to update ensemble-based verification.  Certain upper-air thresholds are defined in both the deterministic and ensemble upper-air conf files, but those should also be consolidated.  

## Solution
Use the deterministic point-stat conf files to define variables, upper-air levels, and thresholds for ensemble verification.   Redefine upper-level thresholds for each model field.

**Comment by jwolff-ncar** [comment]
This was addressed with https://github.com/ufs-community/regional_workflow/pull/649
