### ISSUE TITLE
Pull out machine-specific information to a separate config file.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/regional_workflow#618]
## Description
I'd like to contribute a modification that pulls out as many MACHINE case statements as possible to use machine-specific configuration files that can be used during configuration and run-time so that users running on unsupported platforms do not have to modify scripts at all. 

## Solution
Remove as many MACHINE case statements as possible, and introduce a set of bash config files -- one for each supported machine. These will keep track of variables for machine architecture, run commands, and expected file paths.

## Related to 
Issue #610 -- While changes to address this issue will take into account the ability to run with a linux platform, it will still require quite a bit of script editing. For running automated testing, it will be quite difficult to specify necessary configurations to the existing tests to run on separate platforms.

**Comment by mkavulich** [comment]
Fixed via #666
