### ISSUE TITLE
Update rst documentation for DEBUG variable in PR#639

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#640]
## Description
Update rst documentation for `DEBUG` variable introduced in PR#[639](https://github.com/NOAA-EMC/regional_workflow/pull/639).  Documentation already exists in `config_defaults.sh`.

## Solution
Update the necessary rst file.

## Related to (optional)
PR#[639](https://github.com/NOAA-EMC/regional_workflow/pull/639)

**Comment by mkavulich** [comment]
DEBUG documentation has been updated: https://ufs-srweather-app.readthedocs.io/en/develop/ConfigWorkflow.html?highlight=debug#debug-parameter
