### ISSUE TITLE
Update rst documentation for using template variables

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#651]
## Description:
Update rst documentation for variables introduced in PR #650 for using template variables. Documentation already exists in the WE2E test configuration file `config.template_vars.sh` (in the directory `regional_workflow/tests/WE2E/test_configs/wflow_features`).

## Solution:
Update the necessary rst file.

## Related to:
PR #650.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository as part of new issue: https://github.com/ufs-community/ufs-srweather-app/issues/392
