### ISSUE TITLE
Many WE2E tests do not run successfully with top of develop branch

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/regional_workflow#673]
# Description
Because I was unsure about failures I was seeing in testing for a PR, I ran the entire suite of tests on Hera. I found that with the top of the develop branch, a large number of tests fail on Hera (as well as other platforms). These tests were run with ufs-srweather-app [hash 4120a9bf](https://github.com/ufs-community/ufs-srweather-app/tree/4120a9bf26d711bf26910d3017d0a9e8b1369b26) and compiled with default Intel compilers unless otherwise noted. The Hera tests can be found on disk at `/scratch2/BMC/det/kavulich/workdir/run_all_tests/expt_dirs`

### Hera failures
Here are the tests that are failing on Hera with the 4120a9bf develop hash, including a brief description of the failure. There is an impressively wide variety of failure modes.

 - community_ensemble_008mems, community_ensemble_2mems, subhourly_post_ensemble_2mems
   - All forecast tasks fail (segmentation fault, no descriptive error message)
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio, get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS, grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp, grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional, grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp, new_ESGgrid, specify_DOT_OR_USCORE, subhourly_post
   - run_fcst failure (segmentation fault, no descriptive error message)
   - This is likely related to https://github.com/ufs-community/ufs-weather-model/issues/961
 - get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio
   - Missing initial and boundary conditions
 - grid_RRFS_AK_3km_ics_RAP_lbcs_RAP_suite_GSD_SAR, grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_GSD_SAR, grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GSD_SAR
   - run_fcst failure, "[AVOST IN VILKA](https://github.com/NCAR/ccpp-physics/issues/599)" RUC LSM errors, perhaps due to CFL violations? 
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha, grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
   - run_fcst failure, NaNs in the surface pressure, plus other horribleness
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_CPT_v0
   - run_fcst failure, `invalid reference to variable in NAMELIST input`
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v16, grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2, grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2, nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2, nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
   - run_fcst failure, `FATAL from PE     4: compute_qs: saturation vapor pressure table overflow, nbad=      1`
 - grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GSD_SAR, grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR, grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta
   - errors in make_ics and make_lbcs, `*** FATAL ERROR: packing type 40000 not supported ***`
 - grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha
   - run_fcst failure, `FATAL from PE     0: NetCDF: One or more variable sizes violate format constraints: set_netcdf_mode`

Will provide more details on other platforms later as I have time.

## Steps to Reproduce

 - Build the UFS SRW App with hash 4120a9bf
 - Run the workflow end-to-end tests in tests/WE2E/
 - Observe successes and failures

**Comment by robgonzalezpita** [comment]
@mkavulich I was able to reproduce this issue.  All of the end to end tests you listed as failing above failed for me as well, with the same tasks failing. My record of this can be found on Hera: `/scratch2/BMC/gsd-hpcs/Rob.Gonzalez-Pita/workdir/all_tests/`.

Moving forward, standardizing a suite of tests is crucial to establish a testing framework.  Knowing which of these tests we can expect to pass and which we can expect to fail is imperative in setting up a robust continuous integration environment.

**Comment by christinaholtNOAA** [comment]
Just to chime in with a bit of information about tests on Jet.

It seems that there is no LBCS data for HRRR on Jet, so the tests that are configured for that would not be able to run.

**Comment by mkavulich** [comment]
With the latest version of ufs-srweather-app (https://github.com/ufs-community/ufs-srweather-app/commit/89a0793359674acc0c663f70f15835fd47df6227, RW: https://github.com/ufs-community/regional_workflow/commit/2718b625d9b8cebab6ea79fc1cfb8761aaf8bca0), the test list has changed, as have the list of failing tests. I have documented the new list of failures below (all tests on Hera), along with the current successful tests for completeness sake.

### Successful tests (58)
 - deactivate_tasks
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019101818
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022518
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022600
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2021010100
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019101818
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022518
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022600
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021010100
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2021062000
 - get_from_HPSS_ics_HRRR_lbcs_RAP
 - get_from_HPSS_ics_RAP_lbcs_RAP
 - grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_HRRR_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - GST_release_public_v1
 - inline_post
 - MET_verification
 - nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
 - nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - nco_inline_post
 - new_GFDLgrid
 - new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_FALSE
 - new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_TRUE
 - pregen_grid_orog_sfc_climo
 - specify_DT_ATMOS_LAYOUT_XY_BLOCKSIZE
 - specify_EXTRN_MDL_SYSBASEDIR_ICS_LBCS
 - specify_RESTART_INTERVAL

### Failures (18)
 - community_ensemble_008mems, community_ensemble_2mems, MET_ensemble_verification, nco_ensemble, subhourly_post_ensemble_2mems
   - All run_fcst tasks fail: `FATAL from PE     0: get_ascii_file_num_lines: File input.nml does not exist.`
   - https://github.com/ufs-community/regional_workflow/issues/702
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio, get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS, grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp, grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional, grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp, grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v16, new_ESGgrid, specify_DOT_OR_USCORE, subhourly_post
   -  run_fcst failure (segmentation fault, no descriptive error message)
   - This is likely related to https://github.com/ufs-community/ufs-weather-model/issues/961
 - get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio
   - Failed getting data from NOMADS....this needs to be taken out of the "generate" step!
 - grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR, grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta
   - errors in make_ics and make_lbcs, `*** FATAL ERROR: packing type 40000 not supported ***`
 - grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha
   - run_fcst failure (near the end of the forecast period, 5 of 6 hours complete successfully), `FATAL from PE     0: NetCDF: One or more variable sizes violate format constraints: set_netcdf_mode`

**Comment by JacobCarley-NOAA** [comment]
@mkavulich for the last failure noted (`FATAL from PE 0: NetCDF: One or more variable sizes violate format constraints: set_netcdf_mode`), the following might work for you as we had similar issues with the large North American domain and the following namelist change, suggested by GFDL, fixed it:

&fms2_io_nml
netcdf_default_format="netcdf4"
/

**Comment by gsketefian** [comment]
@mkavulich I noted [here](https://github.com/ufs-community/regional_workflow/issues/705#issuecomment-1071890510) that 9 of the 18 tests involving the `GFS_2017_gfdlmp[_regional]` suite that are currently failing should pass once Issue #705 is addressed.

**Comment by chan-hoo** [comment]
@mkavulich, PR #706 will fix the failures on 
- get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio 
- get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS
- new_ESGgrid
- specify_DOT_OR_USCORE
- grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp
- grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
- grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp 

, and I expect that the failures on the following two tests will be resolved once PRs #704 and #706 are merged 
- community_ensemble_008mems
- community_ensemble_2mems

**Comment by mkavulich** [comment]
Using the latest regional_workflow hash (which has not yet been added to the SRW develop branch), the vast majority of tests now pass on Hera.  
 - community_ensemble_008mems
 - community_ensemble_2mems
 - deactivate_tasks
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019101818
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022518
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022600
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2021010100
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019101818
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022518
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022600
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021010100
 - get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2021062000
 - get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS
 - get_from_HPSS_ics_HRRR_lbcs_RAP
 - get_from_HPSS_ics_RAP_lbcs_RAP
 - grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_HRRR_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR
 - grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
 - grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_HRRR
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
 - grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
 - grid_RRFS_NA_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta
 - grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha
 - grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
 - GST_release_public_v1
 - inline_post
 - MET_ensemble_verification
 - MET_verification
 - nco_ensemble
 - nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
 - nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
 - nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
 - new_ESGgrid
 - new_GFDLgrid
 - new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_FALSE
 - new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_TRUE
 - pregen_grid_orog_sfc_climo
 - specify_DOT_OR_USCORE
 - specify_DT_ATMOS_LAYOUT_XY_BLOCKSIZE
 - specify_EXTRN_MDL_SYSBASEDIR_ICS_LBCS
 - specify_RESTART_INTERVAL
 - specify_template_filenames

There are four tests that still fail on Hera:
 - get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio
 - grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v16
 - subhourly_post
 - subhourly_post_ensemble_2mems

I will close this issue and open individual issues for the remaining failed tests
