### ISSUE TITLE
The directories of UFS SRW App should be renamed and workflow env files needs to be moved to regional workflow

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/regional_workflow#678]
## Description
- Some directories in UFS SRW App should be renamed to meet the NCO standards and the regional workflow needs to be updated for this.
- The workflow env files in 'ufs-srweather-app/env' need to be moved into the regional workflow.

**Comment by JeffBeck-NOAA** [comment]
Hi @chan-hoo, can you explain more about why this is necessary?  Thanks.

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, The wflow_[machine].env files are used only when a new workflow is generated and the launch script runs. They are not used at all when the app is built. So they don't need to exist on the app level but they should exist inside the workflow. They are totally dependent to the regional workflow.
