### ISSUE TITLE
Fix UPP namelist

### ISSUE THREAD

**Issue by hertneky** [ufs-community/regional_workflow#687]
# Description

A typo in the UPP namelist is missing the "/" character after the model_inputs section. This is not caught by Intel, but is caught by GNU.

## Steps to Reproduce

1. Run SRW develop with GNU on cheyenne
2. Error in UPP logfile

Note: Once this is resolved, another error occurs, unrelated to the namelist issue. (Also uncovered only with GNU compiler) Will be separate issue. It is related to reading a variable into UPP, and is currently unclear if it is a UPP issue or an issue with the model input for that variable.

**Comment by gsketefian** [comment]
@hertneky Just wanted to point out that the UPP tasks are currently failing on Jet and Cheyenne (but not Hera).  See PR #692 and #689 reports something similar.  I don't know if this is the same problem that you already mentioned above...

**Comment by hertneky** [comment]
@gsketefian  Assuming an updated hash is being used for the regional workflow (c4a5007)? I tested this myself on Cheyenne and Hera (I don't have allocations to run jobs on other machines currently)

**Comment by hertneky** [comment]
@gsketefian I just did a quick test of latest SRW App on cheyenne intel and all was good. Feel free to point me to your directory if you are still having issues. (Note this issue should be closed with PR688 which was already merged)

**Comment by gsketefian** [comment]
@hertneky Thanks Tracy.  It looks like an older hash is what's being used in regional_workflow.  I will get the latest and retry.  I'll let you know if it's still failing.

**Comment by hertneky** [comment]
@gsketefian I cloned a fresh develop branch of SRW App and all hashes were good. I made no changes. Hope it works for you.

**Comment by gsketefian** [comment]
@hertneky After making sure I updated all my hashes, everything runs fine on Jet and Cheyenne.  Thanks!  I'll close this issue now.
