### ISSUE TITLE
Non-SPP ensemble tests fail

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/regional_workflow#702]
# Description

All WE2E ensemble tests (community_ensemble_008mems, community_ensemble_2mems, subhourly_post_ensemble_2mems, nco_ensemble, MET_ensemble_verification) now fail after commit 03a0eedaf (#685).

This appears to be related to the new SPP logic, as the "settings" variable is not set correctly in the run_fcst step:

```
The variable "settings" is empty, so not setting any namelist values.
```

This results in `input.nml` not being available for the model to run

```
 af nems config,dt_atmos=          40 nfhmax=   6.000000
 in fcst comp init, fcst_ntasks=          10
 af nems config,num_restart_interval=           1
 af nems config,restart_interval=  0.0000000E+00

FATAL from PE     0: get_ascii_file_num_lines: File input.nml does not exist.


FATAL from PE     0: get_ascii_file_num_lines: File input.nml does not exist.

Image              PC                Routine            Line        Source
ufs_model          00000000041471EA  Unknown               Unknown  Unknown
ufs_model          00000000029CB37C  mpp_mod_mp_mpp_er          71  mpp_util_mpi.inc
ufs_model          00000000029C2638  mpp_mod_mp_get_as        1498  mpp_util.inc
ufs_model          00000000029C1DE3  mpp_mod_mp_read_i        1352  mpp_util.inc

. . .
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run one of the affected WE2E tests on a supported platform
2. Observe failures at the "run_fcst" steps

## Output

The full log file for the "community_ensemble_008mems" test, member 1, cycle 1 is attached. All other failures give similar results

[run_fcst_mem001_2019070100.log](https://github.com/ufs-community/regional_workflow/files/8257407/run_fcst_mem001_2019070100.log)

**Comment by JeffBeck-NOAA** [comment]
Subhourly_post_ensemble_2mems WE2E failing, but unrelated to previous non-SPP ensemble WE2E test failures.
