### ISSUE TITLE
Make divergence damping parameters in FV3 namelist suite-specific

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#705]
# Description

In PR #657, the following parameters were changed in `input.nml.FV3` (which applies to all suites):
```
nord: 2 -> 3
d4_bg: 0.15 -> 0.12
```
This breaks the WE2E tests for the `GFS_2017_gfdlmp` and `GFS_2017_gfdlmp_regional` suites.

## Steps to Reproduce
Run the app on the test `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp`.  Other tests that use the  `GFS_2017_gfdlmp` and `GFS_2017_gfdlmp_regional` suites can also be run to confirm that they fail.

## Additional Context
The failed tests were rerun with the `nord` and `d4_bg` parameters reset to their original values (2 and 0.15), and they completed successfully.

**Comment by gsketefian** [comment]
@chan-hoo When you made the changes in PR #657, did you mean for them to apply to all suites?

**Comment by gsketefian** [comment]
For the record, here is the chat from the code management meeting on 3/17/2022:
```
Benjamin Blake - NOAA Affiliate10:36 AM
I think vtdm4 can be changed seperately

Jacob Carley - NOAA Federal10:37 AM
       nord =  3
       d4_bg = 0.12
       vtdm4 = 0.02

Benjamin Blake - NOAA Affiliate10:37 AM
But changing it from 0.075 to 0.02 does greatly improve model stability as Jacob noted

Jacob Carley - NOAA Federal10:45 AM
@Mike, we have run into that netcdf error before.
here is the fix we got from GFDL: 

Please add the following to your namelist settings:

&fms2_io_nml
netcdf_default_format="netcdf4"
/

Testing our infrastructure with files of the size you are using and this namelist setting no longer fail due to internal NetCDF limits associated with the older NetCDF v3 formats.

Jacob Carley - NOAA Federal10:46 AM
it's related to the giant sizes with the NA domain.
```

**Comment by chan-hoo** [comment]
@gsketefian, I am sorry for my change caused this issue. I realized that I didn't test 'GFS_2017_gfdlmp' then. Regarding your question: I mainly targeted three ccpp suites; GFS_v15_thompson_mynn_lam3km, GFS_v15p2, and GFS_v16. Let me know if there is anything I can help you with. Do you want me to take care of this issue?

**Comment by gsketefian** [comment]
@chan-hoo No problem, and thanks for the clarification.  

Why don't we then change `input.nml.FV3` back to the old values of `d4_bg` and `nord` and instead make the changes in `FV3.input.yml` only for the 3 suites you mention?

For the `vtdm4` parameter, it looks like the `GFS_v16` suite already has that set to 0.02 in `FV3.input.yml`, but `GFS_v15_thompson_mynn_lam3km` and `GFS_v15p2` do not.  From what @BenjaminBlake-NOAA and @JacobCarley-NOAA said, it seems we should add this change to in `FV3.input.yml` for those two suites as well.

These changes would require rerunning many of the suites again.  @mkavulich has results from the full set of tests in Issue #673.  I've also been running many tests and found that all of the `GFS_2017_gfdlmp[_regional]` tests that are currently failing will work again with the `d4_bg` and `nord` changes.  These tests are (9 of them):
```
community_ensemble_008mems
community_ensemble_2mems
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio
get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS
new_ESGgrid
specify_DOT_or_USCORE
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp
```
So that should reduce the number of failing tests that @mkavulich found from 18 to 9.

I am (1) out all of next week and (2) am running out of core-hours (my jobs take forever to start now), so it would be a great help if you could make a PR for this fix.  Thanks very much.

**Comment by chan-hoo** [comment]
@gsketefian, I think that the new parameter values would be necessary for the other RRFS_v* suites too. I'll change the values only for the 'GFS_2017_gfdlmp*' suites back to the original ones and test all the suites.
