### ISSUE TITLE
WE2E testing does not support GNU compilers

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/regional_workflow#710]
# Description

The run_WE2E_tests.sh defaults to "intel" compilers and cannot run the SRW when built with GNU compilers.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Build SRW with GNU compilers on cheyenne
2. Attempt to run the grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha case with the E2E testing
3. make_grid will fail because the intel modules are loaded.

**Comment by mkavulich** [comment]
Resolved by #711
