### ISSUE TITLE
Update config.*sh file templates for v2 release

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/regional_workflow#714]
## Description
Currently, config.*.sh files in regional_workflow/ush use GFSv15p2 physics suite - this will not be supported for v2 release 

The path to the staged data (example of Hera is used here) in config*.sh points to 
/scratch2/BMC/det/UFS_SRW_app/v1p0/model_data/FV3GFS
The purpose of having a static version (rather than pointing to develop) is that as things change going forward it will not break what is needed for the specific release. 

## Solution
Change GFSv15p2 to GFSv16 (and test!)

The v1p0 should be updated using one of two options 1) a copy of develop should be used to create a v2p0 or 2) point the example to develop.

**Comment by natalie-perlin** [comment]
@jwolff-ncar - is there a specific repo for the GFSv15p16 physics option?.. It is not found anywhere in the code when searching through the "develop" branch of ufs-weather-model/FV3/ccpp/physics/.

**Comment by gspetro-NOAA** [comment]
@natalie-perlin I think you just need to update the config shell scripts in ufs-srweather-app/regional_workflow/ush and also any machine-specific config scripts to say GFSv16 instead of GFSv15p2. (Ideally, you'd also update anything else for the release, like new data/file paths and such, I believe.) But @jwolff-ncar can confirm.

**Comment by JeffBeck-NOAA** [comment]
@natalie-perlin, setting CCPP_PHYS_SUITE in your config.sh file tells the App to go grab that specific XML in the ufs-weather-model source directory and copy it to the run directory during the workflow generation step.  It also determines the namelist structure and certain flags for pre-processing.

**Comment by JeffBeck-NOAA** [comment]
This issue was resolved in `PR #746`, but it still needs to be merged into the release branch.

**Comment by natalie-perlin** [comment]
config.community.sh, config.nco.sh are updated.

**Comment by jwolff-ncar** [comment]
@JeffBeck-NOAA It doesn't look like config.nco.sh is updated in the other PR so we need to make sure that also gets included prior to merge.

**Comment by JeffBeck-NOAA** [comment]
Thanks @jwolff-ncar, I just left a note in the PR conversation after seeing your comment.  Hopefully @natalie-perlin can take a look.

**Comment by natalie-perlin** [comment]
Closing the issue, all updated
