### ISSUE TITLE
Add percentile thresholding into verification tasks

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/regional_workflow#719]
## Description
Enhance the verification tasks to also use percentile thresholding in addition to the current absolute thresholding to account for bias.

## Solution
Modifications need to be made to the METplus conf files to include this option.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/383
