### ISSUE TITLE
Update diag table to use consistent/unified output names for RRFS, HAFS, and GFS applications

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [ufs-community/regional_workflow#722]
## Description
A handful of variables have different output names for different applications.  This creates confusion and cause UPP and DA code managers having to maintain different read interfaces.

## Solution
I have identified these variables and coordinated with RRFS, HAFS, and GFS implementation managers to agree on unified output names to use

## Alternatives (optional)
none

## Related to (optional)
After implementation managers and Physics group agreed to the same output names, Wen has created an issue PR #[453](https://github.com/NOAA-EMC/UPP/pull/453) on unifying UPP stand-alone FV3 global and regional interfaces.  The work
has been completed recently.  She will work on unifying UPP FV3 inline interfaces next.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/390
