### ISSUE TITLE
Increase size of RRFS CONUS 3-km grid

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [ufs-community/regional_workflow#723]
## Description
The size of the 3-km CONUS grid needs to be increased in order to produce output on the operational HRRR / NAM nest grid without undefined points.  This grid will be used by the RRFS real-time parallels.

## Solution
The name of the grid will be kept as RRFS_CONUS_3km.  The current RRFS_CONUS_3km grid will be kept in the workflow for any users who wish to continue using it.  In addition, the corresponding 13-km and 25-km RRFS CONUS grids will be modified to match the size increase of the 3-km grid.

**Comment by JeffBeck-NOAA** [comment]
Resolved in [PR #724](https://github.com/ufs-community/regional_workflow/pull/724).
