### ISSUE TITLE
Remove COMINgfs from workflow

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#735]
## Description
PR #713 has changed the tests so that in NCO mode, `COMINgfs` (`TEST_COMINgfs` in the machine files) is no longer used in the workflow.  Also, `USE_USER_STAGED_EXTRN_FILES` is now used instead 

## Solution
Remove `COMINgfs` from workflow (?).

**Comment by gsketefian** [comment]
@chan-hoo Do you really want to get rid of `COMINgfs` from the workflow?  The directory `TEST_COMINgfs` in `machine/hera.sh` is not used at all:
```
TEST_COMINgfs="/scratch2/NCEPDEV/fv3-cam/noscrub/UFS_SRW_App/COMGFS"
```
@mkavulich FYI.

**Comment by chan-hoo** [comment]
@gsketefian, I've never talked about "COMINgfs" before. The "COMINgfs" should not be removed from the workflow. It should be renamed to "COMIN" though. I'll open a PR for the vertical structure of the "nco" mode later.

**Comment by gsketefian** [comment]
@chan-hoo In that case, all the nco tests need to be using `COMINgfs` (or just `COMIN`).  `USE_USER_STAGED_EXTRN_FILES` should not be set in the NCO tests; it should be left to its default value of "FALSE".

**Comment by chan-hoo** [comment]
@gsketefian, I understand what your point is now. The vertical structure of the 'nco' mode should be updated. I just started working on it, so it will take some time. Until the vertical structure is set up correctly, I think we'll need to use `USE_USER_STAGED_EXTRN_FILES`. I think the 'nco' mode is not relevant to this release. I agree with you. It should be modified eventually. If this is not an urgent issue, please give me some time.

**Comment by chan-hoo** [comment]
@gsketefian, I'll close this issue.
