### ISSUE TITLE
Move fixed-file mapping variables (e.g. `FV3_NML_VARNAME_TO_SFC_CLIMO_FIELD_MAPPING`) out of `config_defaults.sh`

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#737]
## Description
Move fixed-file mapping variables (e.g. `FV3_NML_VARNAME_TO_SFC_CLIMO_FIELD_MAPPING`) out of `config_defaults.sh` and into `setup.sh` or other scripts since these variables are not ones that would usually be changed by a user.

**Comment by gsketefian** [comment]
@gspetro-NOAA Just tagging you so you are aware that this issue exists.

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/367
