### ISSUE TITLE
Export environment variables/parameters to subshells

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/regional_workflow#753]
## Description
Parameters defined in `var_defns.sh` and other similar scripts are accessible only from the current shell it is sourced into, not sub-shells or python scripts that maybe called from that script later. This is because the parameters in `var_defns.sh` do not have EXPORT statements. At the moment, every support shell script is sourced into the main script, so the latter is essentially one giant script. I am not sure this is a deliberate choice, but it makes it hard to access parameters defined in `var_defns.sh` in subshells and python scripts.

## Solution
A potential solution
```sh
set -a
source var_defns.sh
set +a
```

## Alternatives (optional)
None

## Related to (optional)
None

**Comment by gsketefian** [comment]
@danielabdi-noaa Yes, not exporting was a deliberate choice in order to avoid conflict/overwriting with other local variables, and to avoid changing of these variables once they are by the experiment generation.  Any sub-script that needs access to these generally gets them via an argument list (usually the sub-script needs access to just a handful).

**Comment by danielabdi-noaa** [comment]
@gsketefian Thanks for the info, that was exactly what I was afraid of. I will look for a better solution then! Thanks

**Comment by gsketefian** [comment]
@danielabdi-noaa When I decided not to make all the variables global (using `export`), I was thinking of the way variables and functions can be compartmentalized in FORTRAN using modules (`module use ...`).  It seems to me making all variables available everywhere is like using `COMMON`s in old FORTRAN, which is nowadays considered bad form.

Do you have a specific example of something you're trying to do where you need access to more than a few variables?

**Comment by danielabdi-noaa** [comment]
@gsketefian The particular example I was working on relates to calling `python3 get/delete_crontab_contents.py`. A straightforward port of the shell script version of the same file in python expects parameters `[ MACHINE, USER, CRONTAB_LINE, SED ]` from the environment. Also, same problem exists, if the shell script version is called in a subshell  `( ./delete_crontab_line.sh )` -- for which there is really no need so we can avoid subshells. However, calling a python script is sort of a forced subshell call, so I will have to pass those four  parameters via arguments. There are already python scripts called from job scripts such as `set_namelist.py`, `fill_jinja_template.py` etc.., but they get evreything they need all to passed through their arguments.

**Comment by mkavulich** [comment]
Discussion has been resolved
