### ISSUE TITLE
The plot_allvars.py script is broken after post filename change

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/regional_workflow#781]
The post is producing files that look like rrfs.t18z.natlev.f000.indy.grib2, where "indy" is the name of the POST_OUTPUT_DOMAIN_NAME. Unfortunately, plot_allvars is looking for files with a format of rrfs.t18z.natlev.f000.tm00.grib2.

A new command line argument containing the POST_OUTPUT_DOMAIN_NAME should be added to plot_allvars.sh.

In addition, some CI/CD tests should be added to test the plotting capability going forward.

**Comment by dmwright526** [comment]
@mark-a-potts, this should be a pretty quick fix. I can go ahead and modify plot_allvars.sh and plot_allvars_diff.sh. I am going to assume you want this for v2 release, so do you want to fix and documentation update applied to develop and/or release/public-v2?

**Comment by mark-a-potts** [comment]
That would be great. I actually tested out a fix earlier that just added another variable to the command line arguments, but haven't had time to put in a PR for it. I only modified plot_allvars.py, though. If you don't mind putting in the fix, I'd appreciate it. 

EPIC is working on adding some plotting capabilities to the e2e testing where at least some plots would get generated at the end of each test and uploaded as an artifact that can be viewed through the jenkins portal. Somebody will still need to look at the plots to see if they look reasonable, but it should catch issues like this, where plotting gets broken, going forward.

**Comment by gsketefian** [comment]
@dmwright526 @mark-a-potts Hey guys, I went ahead and made a basic set of fixes already (didn't realize @dmwright526 had started on it).  I feel an urgency to get this fixed since it has to be ready for the AMS Short Course on Monday.

**Comment by dmwright526** [comment]
Thanks @gsketefian (this saved me some time this evening)!

**Comment by mkavulich** [comment]
Resolved by #783
