### ISSUE TITLE
Machine files need to be updated/data staged for release

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/regional_workflow#793]
## Description
In the release branch all machine files point to a ``UFS_SRW_App/develop`` directory on each platform. If the release goes out pointing to develop, future updates to static data/fix files as develop moves forward could cause failures for community users using the release code.

## Solution
This should be updated (and the appropriate data staged) to ``UFS_SRW_App/v2.0`` or something similar

To avoid data duplication, the current contents "develop" can be moved to the location of the release staged data, and replaced with symbolic links until updates are needed to that data. This should be done on a file-by-file basis so that individual files can be updated to non-symlinks in "develop", preventing as much data duplication as possible.

**Comment by mkavulich** [comment]
I have staged data in "standard" locations on the following machines:

 - Cheyenne ``/glade/p/ral/jntp/UFS_SRW_App/v2p0``
 - Hera ``/scratch2/BMC/det/UFS_SRW_App/v2p0``
 - Jet ``/mnt/lfs4/BMC/wrfruc/UFS_SRW_App/v2p0``
 - Orion ``/work/noaa/fv3-cam/UFS_SRW_App/v2p0``

I do not have access to stage the data on other platforms, so someone else will have to stage that data.

**Comment by mark-a-potts** [comment]
I'll change the name to match on Gaea.

**Comment by gspetro-NOAA** [comment]
I copied the release data to a v2p0 directory on the three NOAA Cloud systems. :)
