### ISSUE TITLE
Run WE2E script checks for ICS and LBCS contain flawed logic.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/regional_workflow#807]
# Description
The logic in `tests/WE2E/run_WE2E_tests.sh` regarding setting and checking `EXTRN_MDL_SYSBASEDIR_ICS` and `EXTRN_MDL_SYSBASEDIR_LBCS` starting around line 1205 is flawed and somewhat unnecessary.

The `EXTRN_MDL_SYSBASEDIR_*` directories on the platforms are not used in the test framework, except when it is set to a special string `set_to_non_default_location_in_testing_script` and the value is set in the machine config file. 

The check for the existence of the path that is not used -- and may not exist -- hampers the true intent of the test in question if there is user-staged file paths, for example, or if the files should be pulled from AWS or HPSS. 

An alternative solution is to only check that the file path exists if it is set as the location needed for the test framework. 

I suggest that additional low-cost "platform tests" be added to the testing framework and that the _only_ thing they do is check that any path set in the machine config file is verified to exist. That will give us some heads up that something on the machine changes, but won't get in the way of the WE2E tests when it is mostly irrelevant. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set a value for `EXTRN_MDL_SYSBASEDIR_LBCS` in a machine file that does not exist, or isn't readable.
2. Run tests/WE2E/run_WE2E_tests.sh on that machine
3. Observe a failure that looks like this:

```
ERROR:
 From script: “run_WE2E_tests.sh”
 Full path to script: “/scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/944949396/20220617165015/ufs-srweather-app/regional_workflow/tests/WE2E/test_configs/wflow_features/run_WE2E_tests.sh”
The non-default location specified by EXTRN_MDL_SYSBASEDIR_ICS does not
exist or is not a directory:
 EXTRN_MDL_NAME_ICS = “FV3GFS”
Exiting with nonzero status.
```

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/364
