### ISSUE TITLE
Placeholder issue for work on making J-jobs production standard compliant 

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [ufs-community/regional_workflow#811]
## Description
The current regional workflow J-jobs lack use of certain standard variable names needed in production J-jobs
## Solution
Modify these jobs to include the needed missing definitions.  I will work on some prototype changes.
## Alternatives (optional)
N/A
## Related to (optional)
TBD

**Comment by mkavulich** [comment]
Issue migrated to ufs-srweather-app repository: https://github.com/ufs-community/ufs-srweather-app/issues/366
