### ISSUE TITLE
Create a single yaml file each for diag_table and field_table

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/regional_workflow#821]
## Description
We currently have nine diag_table and nine field_table template files that are specific to the CCPP SDF selected by the user.

## Solution
Consolidating this information into two yaml files would simplify the template directory and provide a single location for changes.

**Comment by christinaholtNOAA** [comment]
Both of these file types are CSV-like formats. What are your ideas on how the information should be stored concisely as a key/value structure?

**Comment by JeffBeck-NOAA** [comment]
Maybe a single jinja template would be better for these two files?  Different blocks of entries would apply to different CCPP SDFs.  I can see how a key/value structure doesn't lend itself well in this case.
