### ISSUE TITLE
Multiple issues related to METplus conf files

### ISSUE THREAD

**Issue by michelleharrold** [ufs-community/regional_workflow#825]
# Description

In PointStat_upper_air_mean.conf verification for DPT at 700 hPa is set incorrectly:

FCST_VAR5_NAME = DPT_P850_ENS_MEAN
FCST_VAR5_LEVELS = P700
FCST_VAR5_THRESH = >=263, >=286, >=273

In addition, while fixing this, it was discovered the VARn_LEVELS was inconsistently set in the mean and prob conf files for METplus grid-to-point verification. This issue doesn't affect output (MET doesn't actually read the level in this case), but it could lead to confusion down the road.

## Steps to Reproduce

Run the workflow in its current state, the the 700 hPa dew point verification for ensemble mean metrics will actually be for 850 hPa!

## Additional Context

None.

## Output

None.

**Comment by mkavulich** [comment]
Resolved by #826
